### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by Elbehery** [CoprHD/CoprHD.github.io#1]
I would like to contribute to the project, I am waiting for first task. Sorry to use issues, there is no direct messages :)

**Comment by urayoan** [comment]
Hi! :)

Make sure to go over to the google group and add yourself to it. That way you'll know right away once we bring the code over to Github. Should be in early June.

Between now and then, we'll update the wiki with more information and the Jira with some tasks, etc.

Thank you so much for your interest! :)
Ura
